# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Woran4ik.MinerSimulator
PackageVersion: beta 2
InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Woran4ik/Miner-Simulator/releases/download/beta2/MinerSimulator_Setup_v2_Beta.exe
  InstallerSha256: E6D2FEACFAC9C2D1259FFACE5FF55EFE3C592461F4F9EE983AAE418A38BB2BB8
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-04
