# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Woran4ik.MinerSimulator
PackageVersion: beta 2
PackageLocale: ru-RU
Publisher: Woran4ik
PublisherUrl: https://github.com/Woran4ik
PublisherSupportUrl: https://github.com/Woran4ik/Miner-Simulator/issues
PackageName: Miner Simulator
PackageUrl: https://github.com/Woran4ik/Miner-Simulator
License: MIT
ShortDescription: A simulator game about mining resources and upgrading equipment.
ReleaseNotesUrl: https://github.com/Woran4ik/Miner-Simulator/releases/tag/beta2
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/Woran4ik/Miner-Simulator/wiki
ManifestType: defaultLocale
ManifestVersion: 1.12.0
